/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Bionic.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _Bionic_H
#define _Bionic_H

#ifdef __cplusplus
  extern "C" {
#endif


/*******************************************************************
 * General functions
 *******************************************************************/

/*
 * returns the size of a length delimited message which also 
 * contains the first bytes for the length encoding.
 */
unsigned long Message_get_delimited_size(void *_buffer, int offset);

/*
 * Tests whether a message can be completely read from the given buffer at
 * the offset. The bytes [offset..offset+length-1] are interpreted.
 *
 * Returns 1 (true) if buffer[offset..offset+length-1] contains a complete
 * message or 0 (false) otherwise.
 */
int Message_can_read_delimited_from(void *_buffer, int offset, unsigned int length);


/*******************************************************************
 * Enumeration: Bionic.proto, line 4
 *******************************************************************/
enum ControlType {
    _ANIMATION_CHANGE = 0,
    _PARAMETER_CHANGE = 1
};



/*******************************************************************
 * Message: Bionic.proto, line 12
 *******************************************************************/

/* Maximum size of a serialized CentralControl-message, useful for buffer allocation. */
#define MAX_CentralControl_SIZE 11

/* Structure that holds a deserialized CentralControl-message. */
struct CentralControl {
    enum ControlType _controlType;
    float _controlParameter;
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int CentralControl_write_delimited_to(struct CentralControl *_CentralControl, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int CentralControl_write_with_tag(struct CentralControl *_CentralControl, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int CentralControl_read_delimited_from(void *_buffer, struct CentralControl *_CentralControl, int offset);


/*******************************************************************
 * Message: Bionic.proto, line 10
 *******************************************************************/

/* Maximum size of a serialized CentralControlsReport-message, useful for buffer allocation. */
#define MAX_CentralControlsReport_SIZE 2

/* Structure that holds a deserialized CentralControlsReport-message. */
struct CentralControlsReport {
};

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int CentralControlsReport_write_delimited_to(struct CentralControlsReport *_CentralControlsReport, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int CentralControlsReport_write_with_tag(struct CentralControlsReport *_CentralControlsReport, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int CentralControlsReport_read_delimited_from(void *_buffer, struct CentralControlsReport *_CentralControlsReport, int offset);



#ifdef __cplusplus
  }
#endif

#endif

