// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bionicTest.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "bionicTest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace bionicTest {

namespace {

const ::google::protobuf::Descriptor* MotionData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MotionData_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_bionicTest_2eproto() {
  protobuf_AddDesc_bionicTest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "bionicTest.proto");
  GOOGLE_CHECK(file != NULL);
  MotionData_descriptor_ = file->message_type(0);
  static const int MotionData_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotionData, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotionData, yaw_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotionData, pitch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotionData, roll_),
  };
  MotionData_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MotionData_descriptor_,
      MotionData::default_instance_,
      MotionData_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotionData, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MotionData, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MotionData));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_bionicTest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MotionData_descriptor_, &MotionData::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_bionicTest_2eproto() {
  delete MotionData::default_instance_;
  delete MotionData_reflection_;
}

void protobuf_AddDesc_bionicTest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020bionicTest.proto\022\nbionicTest\"B\n\nMotion"
    "Data\022\n\n\002id\030\001 \002(\005\022\013\n\003yaw\030\002 \002(\005\022\r\n\005pitch\030\003"
    " \002(\005\022\014\n\004roll\030\004 \002(\005", 98);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bionicTest.proto", &protobuf_RegisterTypes);
  MotionData::default_instance_ = new MotionData();
  MotionData::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_bionicTest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_bionicTest_2eproto {
  StaticDescriptorInitializer_bionicTest_2eproto() {
    protobuf_AddDesc_bionicTest_2eproto();
  }
} static_descriptor_initializer_bionicTest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MotionData::kIdFieldNumber;
const int MotionData::kYawFieldNumber;
const int MotionData::kPitchFieldNumber;
const int MotionData::kRollFieldNumber;
#endif  // !_MSC_VER

MotionData::MotionData()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:bionicTest.MotionData)
}

void MotionData::InitAsDefaultInstance() {
}

MotionData::MotionData(const MotionData& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:bionicTest.MotionData)
}

void MotionData::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  yaw_ = 0;
  pitch_ = 0;
  roll_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MotionData::~MotionData() {
  // @@protoc_insertion_point(destructor:bionicTest.MotionData)
  SharedDtor();
}

void MotionData::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MotionData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MotionData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MotionData_descriptor_;
}

const MotionData& MotionData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_bionicTest_2eproto();
  return *default_instance_;
}

MotionData* MotionData::default_instance_ = NULL;

MotionData* MotionData::New() const {
  return new MotionData;
}

void MotionData::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MotionData*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(id_, roll_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MotionData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bionicTest.MotionData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_yaw;
        break;
      }

      // required int32 yaw = 2;
      case 2: {
        if (tag == 16) {
         parse_yaw:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &yaw_)));
          set_has_yaw();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_pitch;
        break;
      }

      // required int32 pitch = 3;
      case 3: {
        if (tag == 24) {
         parse_pitch:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pitch_)));
          set_has_pitch();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_roll;
        break;
      }

      // required int32 roll = 4;
      case 4: {
        if (tag == 32) {
         parse_roll:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &roll_)));
          set_has_roll();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bionicTest.MotionData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bionicTest.MotionData)
  return false;
#undef DO_
}

void MotionData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bionicTest.MotionData)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required int32 yaw = 2;
  if (has_yaw()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->yaw(), output);
  }

  // required int32 pitch = 3;
  if (has_pitch()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->pitch(), output);
  }

  // required int32 roll = 4;
  if (has_roll()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->roll(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bionicTest.MotionData)
}

::google::protobuf::uint8* MotionData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:bionicTest.MotionData)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required int32 yaw = 2;
  if (has_yaw()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->yaw(), target);
  }

  // required int32 pitch = 3;
  if (has_pitch()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->pitch(), target);
  }

  // required int32 roll = 4;
  if (has_roll()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->roll(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bionicTest.MotionData)
  return target;
}

int MotionData::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required int32 yaw = 2;
    if (has_yaw()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->yaw());
    }

    // required int32 pitch = 3;
    if (has_pitch()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->pitch());
    }

    // required int32 roll = 4;
    if (has_roll()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->roll());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MotionData::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MotionData* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MotionData*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MotionData::MergeFrom(const MotionData& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_yaw()) {
      set_yaw(from.yaw());
    }
    if (from.has_pitch()) {
      set_pitch(from.pitch());
    }
    if (from.has_roll()) {
      set_roll(from.roll());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MotionData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MotionData::CopyFrom(const MotionData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MotionData::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void MotionData::Swap(MotionData* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(yaw_, other->yaw_);
    std::swap(pitch_, other->pitch_);
    std::swap(roll_, other->roll_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MotionData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MotionData_descriptor_;
  metadata.reflection = MotionData_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace bionicTest

// @@protoc_insertion_point(global_scope)
